version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

mkdocs:
  configuration: docs/mkdocs.yml

python:
    install:
        - requirements: requirements.txt
        - requirements: docs/docs_requirements.txt
