# Example docker-compose file for TimeTagger that uses the published
# Docker image. Shows all options settable via the environment.
#
# !! Make sure to apply your own credentials                  !!
# !! You can use https://timetagger.app/sha1 to generate them !!

version: "3"
services:
  timetagger:
    image: ghcr.io/almarklein/timetagger
    ports:
      - "80:80"
    volumes:
      - ./_timetagger:/root/_timetagger
    environment:
      - TIMETAGGER_BIND=0.0.0.0:80
      - TIMETAGGER_DATADIR=/root/_timetagger
      - TIMETAGGER_LOG_LEVEL=info
      - TIMETAGGER_CREDENTIALS=test:a94a8fe5ccb19ba61c4c0873d391e987982fbbd3  # test:test
