{{ if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "timetagger.fullname" $ }}-secret
type: Opaque
data:
  {{- range $key := .Values.secretEnv }}
  {{ $key.name }}: {{ $key.value | b64enc }}
  {{- end}}
{{ end }}